<?php

return [
    'Main/view' => 'Main/view',
    'Main/create' => 'Main/create',
    'Main/update' => 'Main/update',
    'Main/delete' => 'Main/delete',
    'Gallery/view' => 'Gallery/view',
    'Gallery/create' => 'Gallery/create',
    'Gallery/update' => 'Gallery/update',
    'Gallery/delete' => 'Gallery/delete',
    'About/view' => 'About/view',
    'About/create' => 'About/create',
    'About/update' => 'About/update',
    'About/delete' => 'About/delete',
    'GalleryCategory/view' => 'GalleryCategory/view',
    'GalleryCategory/update' => 'GalleryCategory/update',
    'GalleryCategory/create' => 'GalleryCategory/create',
    'GalleryCategory/delete' => 'GalleryCategory/delete',
    'Post/view' => 'Post/view',
    'Post/update' => 'Post/update',
    'Post/create' => 'Post/create',
    'Post/delete' => 'Post/delete',
    'PostCategory/view' => 'PostCategory/view',
    'PostCategory/update' => 'PostCategory/update',
    'PostCategory/create' => 'PostCategory/create',
    'PostCategory/delete' => 'PostCategory/delete',
    'User/view' => 'User/view',
    'User/update' => 'User/update',
    'User/create' => 'User/create',
    'User/delete' => 'User/delete',
];